### PR TITLE
Increase memory limit during tests.

### PR DESCRIPTION
**Pull request by diosmosis**

### CODE REVIEW

**Comment by diosmosis** [comment]
This was to fix a random UI test failure on travis which I noticed can run out of memory, but it doesn't seem to work...

**Comment by tsteur** [comment]
Sound still good to fix maybe even if it doesn't help fixing the memory issue?

**Comment by diosmosis** [comment]
Actually I think it does fix the random failure, there's just another one where it fails to write to a cache file for a twig template.

**Comment by tsteur** [comment]
👍 feel free to merge and update the submodule in matomo repo

**Pull request merged**
